- CMakeLists.txt
- cmake/gsDataDir.cmake
refactored setting of gsDataDir to its own file
> refactored setting of gsDataDir to its own file

- external/exprtk.hpp
Changed equal_op::process to invoke and return numeric::equal directly
> Changed equal_op::process to invoke and return numeric::equal directly

- examples/mpi_example.cpp
Should fix https://cdash.ricam.oeaw.ac.at/viewBuildError.php?buildid=218663
> fix examples/mpi_example.cpp

- src/gsCore/gsBasis.h
- src/gsCore/gsBulk.h
- src/gsCore/gsCurve.h
- src/gsCore/gsFunctionSet.h
- src/gsCore/gsGeometry.h
- src/gsCore/gsPatchwiseFunction.h
- src/gsCore/gsSurface.h
- src/gsCore/gsVolume.h
- src/gsHSplines/gsHTensorBasis.h
- src/gsNurbs/gsBSplineBasis.h
should be merged soon (already checked in in SVN)
> rename GISMO_UPTR_FUNCTION_FORWARD to GISMO_UPTR_FUNCTION_PURE

- src/gismo.h
- src/gsSolver/gsGradientMethod.h
- src/gsSolver/gsGradientMethod.hpp
- src/gsSolver/gsGradientMethod_.cpp
- unittests/gsIterativeSolvers_test.cpp
to be beside gsConjugateGradient, gsMinimumResiudal, gsGMRes
> add gsGradientMethod

- src/gsCore/gsMemory.h
Otherwise I get problems in devel with compining with GISMO_EXTRA_DEBUG
> Add a missing header to src/gsCore/gsMemory.h

- src/gsSolver/gsSimplePreconditioners.h
- src/gsSolver/gsSimplePreconditioners.hpp
- src/gsSolver/gsSimplePreconditioners_.cpp
nested is alias to const ref, 
the function will not make a copy for gsSparseMatrix<T>, but will make one for anything else (e.g. rowmajor)
> fix argument of free functions

- src/gsMultiGrid/gsGridHierarchy.h
- src/gsMultiGrid/gsGridHierarchy.hpp
+ rename local variable assemblerOptions => options
> add some missing getters to gsGridHierarchy

- src/gsMultiGrid/gsGridHierarchy.h
- src/gsMultiGrid/gsGridHierarchy.hpp
- src/gsMultiGrid/gsGridHierarchy_.cpp
- src/gsNurbs/gsKnotVector.h
- src/gsNurbs/gsKnotVector.hpp
> coarsenKnotVector: move free function to class

- src/gsIO/gsFileData.h
- src/gsIO/gsFileData.hpp
- src/gsIO/gsFileManager.cpp
- src/gsIO/gsFileManager.h
- src/gsUtils/gsUtils.h
Move file system related stuff from gsFileData to gsFileManager
The string tool ends_with is now next to starts_with in gsUtils
> Move file system related stuff from gsFileData to gsFileManager

- extensions/gsIpopt/gsOptProblem.hpp
- optional/gsParasolid_test.cpp
- src/gsIO/gsIOUtils.h
seems to be a problem due to CDASH / seems that there has been a problem with missing changes
> fix include

- src/gsIO/gsFileData.h
- src/gsIO/gsFileData.hpp
The behavior of gsFileData should be similar for the case that the file cannot be found and the case that the file is invalid.
Moreover, it might be of interest to return a bool on gsFileData::read.
So, finally the consumer can (in all cases) just call
if (fd.hasAny< ObjectTypeOfInterest >())
to check all cases (file not existing, invalid file, file without that object).
> Consistency change for gsFileData.h

- src/gsCore/gsBasis.h
- src/gsCore/gsRationalBasis.h
update such that gsBasis::makeNonRational return a gsBasis::uPtr instead of a raw pointer (gsBasis<T> *)
> gsBasis<T> * makeNonRational -> gsBasis::uPtr makeNonRational

- src/gsCore/gsFunction.h
Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.
Code submitted to the stable branch should be clean, well-documented
and free of bugs.
request:
-----
> small typo change in the doxigen documentary

- src/gsCore/gsDebug.h
- src/gsCore/gsLinearAlgebra.h
- src/gsIO/gsCmdLine.cpp
- src/gsMatrix/BlockDiag.h
- src/gsMatrix/gsSparseSolver.h
- src/gsUtils/gsUtils.h
CG is more efficient when using full matrix
> change assert to throw exception, change CG to use full matrix

- examples/fitting_example.cpp
- src/gsCore/gsDofMapper.cpp
- src/gsCore/gsDofMapper.h
- src/gsCore/gsGeometry.h
- src/gsCore/gsGeometry.hpp
- src/gsMatrix/gsMatrix.h
- src/gsModeling/gsCurveLoop.h
- src/gsModeling/gsCurveLoop.hpp
- src/gsModeling/gsPlanarDomain.h
- src/gsModeling/gsTrimSurface.h
- src/gsNurbs/gsTensorBSplineBasis.h
- src/gsTensor/gsTensorBasis.h
- src/gsTensor/gsTensorBasis.hpp
- src/gsUtils/gsPointGrid.h
- src/gsUtils/gsPointGrid.hpp
- src/gsUtils/gsPointGrid_.cpp
remove oboslete constructors from gsMatrix,
add handy members to gsDofMapper
change return types from pointer to gsMatrix
> Change return types, remove obosete codes and minor fixes

- src/gsCore/gsMemory.h
- src/gsModeling/gsCurveLoop.h
- src/gsModeling/gsCurveLoop.hpp
- src/gsModeling/gsPlanarDomain.h
- src/gsModeling/gsPlanarDomain.hpp
- src/gsModeling/gsSolid.hpp
- src/gsModeling/gsTrimSurface.h
* add another memory::make_unique implementation
* refactor gsPlanarDomain to return gsMatrix<T> instead raw pointer
> fixing gsplanardomain and gscurveloop

- examples/adaptRefinementThb_example.cpp
- examples/adaptiveConvectionDiffusionReaction_example.cpp
- examples/assembly_example.cpp
- examples/bSplineCurve_example.cpp
- examples/fitting_example.cpp
- examples/gsView.cpp
- examples/heatEquation_example.cpp
- examples/poisson2_example.cpp
- examples/poissonTHB_example.cpp
- examples/poisson_example.cpp
- examples/thbSplineBasis_example.cpp
- src/gsCore/gsDebug.h
- src/gsIO/gsFileManager.cpp
- src/gsIO/gsFileManager.h
- src/gsUtils/gsStopwatch.h
3 small improvements in 3 commits
> Small improvements

- doc/Examples.dox
- doc/biharmonic_example.dox
- doc/multiGrid_example.dox
- doc/poisson2_example.dox
- examples/linearSolvers_example.cpp
- examples/multiGrid_example.cpp
- examples/poisson2_example.cpp
- src/gismo.h
- src/gsAssembler/gsAssembler_.cpp
- src/gsSolver/gsBlockOp.h
- src/gsSolver/gsBlockOp.hpp
- src/gsSolver/gsBlockOp_.cpp
- src/gsSolver/gsConjugateGradient.h
- src/gsSolver/gsConjugateGradient.hpp
- src/gsSolver/gsConjugateGradient_.cpp
- src/gsSolver/gsGMRes.h
- src/gsSolver/gsGMRes.hpp
- src/gsSolver/gsGMRes_.cpp
- src/gsSolver/gsGradientMethod.h
- src/gsSolver/gsGradientMethod.hpp
- src/gsSolver/gsGradientMethod_.cpp
- src/gsSolver/gsLinearOperator.h
- src/gsSolver/gsMinimalResidual.h
- src/gsSolver/gsMinimalResidual.hpp
- src/gsSolver/gsMinimalResidual_.cpp
- src/gsSolver/gsSimplePreconditioners.hpp
- src/gsSolver/gsSimplePreconditioners_.cpp
remove wrong GISMO_EXPORT
fixes for doxygen
remove licence header from "*_.cpp"
smaller enhancements in examples
> several fixes

- src/gsSolver/gsMatrixOp.h
- unittests/gsMatrixOp_test.cpp
This now only consists of removing sym and unittests
> Remove sym from gsMatrixOp; add unittest

- src/gsIO/gsFileManager.cpp
- src/gsIO/gsFileManager.h
it is useful to add to existing paths, instead of replacing the existing ones.
> add gsFileManager::addSearchpaths

- src/gsSolver/gsKroneckerOp.h
- src/gsSolver/gsKroneckerOp_.cpp
- unittests/gsKronecker_test.cpp
It was good if we test that operator
> gsKroneckerOp: Test + some explaination

- src/gsCore/gsBoundary.h
> add patchSide::getContainedCorners (int dim, std::vector<patchCorner> &corners)

- examples/poisson2_example.cpp
- src/gsAssembler/gsGaussRule.h
- src/gsAssembler/gsGaussRule.hpp
- src/gsAssembler/gsLobattoRule.h
- src/gsAssembler/gsLobattoRule.hpp
- src/gsAssembler/gsQuadRule.h
- src/gsAssembler/gsQuadrature.h
- src/gsModeling/gsCurveFitting.h
- unittests/gsQuadratureRules_test.cpp
- unittests/main.cpp
add gsQuadratureRules_test
modified gsQuadRule and derivations
> Gs quadrature rules test

- unittests/CMakeLists.txt
> update md5 hash for gsUnitTest

- unittests/gsQuadratureRules_test.cpp
> add referenceWeights checks

- cmake/ctest_script.cmake
- doc/Tutorial04.dox
- src/gsCore/gsBasis.hpp
- src/gsCore/gsDofMapper.cpp
- src/gsCore/gsFunctionSet.hpp
- src/gsHSplines/gsHTensorBasis.h
- src/gsIO/gsFileData.hpp
- src/gsIO/gsXml.cpp
- src/gsNurbs/gsBSplineAlgorithms.h
- src/gsNurbs/gsBoehm.hpp
- src/gsNurbs/gsNurbs.dox
- src/gsNurbs/gsTensorBSpline.hpp
- src/gsUtils/gsSortedVector.h
> fix typos found from lintian

- doc/Tutorial01.dox
- doc/Tutorial02.dox
- examples/commandLineArg_example.cpp
- external/Eigen/src/Core/DenseBase.h
- external/Eigen/src/Core/MathFunctions.h
- external/Eigen/src/Core/Matrix.h
- external/Eigen/src/Core/PlainObjectBase.h
- external/Eigen/src/Core/functors/StlFunctors.h
- external/Eigen/src/Core/util/Constants.h
- external/Eigen/src/SparseCore/SparseSelfAdjointView.h
- src/gsCore/gsFunction.h
- src/gsMultiGrid/gsMultiGrid.hpp
> Spell check

- src/gsSolver/gsLanczosMatrix.h
Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.
Code submitted to the stable branch should be clean, well-documented
and free of bugs.
request:
-----
> fix in file gsLanczosMatrix.h

- changelog
(parsed automatically by ruby script)
NEW: changelog file
FIX: OpenMP features (Pardiso options, use in assemblers)
NEW: Kronecker product of matrices
NEW: Gauss-Lobatto rules
IMPROVED: ctest and cmake scripts
FIXED: memory and pointer handling
NEW: expression assembler
NEW: multigrid with standard smoothers
IMPROVED: unittest framework, made unittest++ external package
FIX: performance bug in gsFitting
IMPROVED: templatized iterative solvers
IMPROVED: file handling using gsFileManager
IMPORVED: use of C++11 move semantics (with C++98 compatibility) as well as unique pointers
NEW: spectra plugin for sparse eigenvalue problems
IMPROVED: zlib external handling (option to use system installed dynamic library)
> add the changelog file and comments for next release

- CMakeLists.txt
- cmake/gsConfig.cmake
- cmake/gsJITConfigXml.cmake
- cmake/gsOptions.cmake
- cmake/jit.xml.in
- extensions/gsUnum/CMakeLists.txt
- extensions/gsUnum/exprtk_unum_posit_adaptor.hpp
- extensions/gsUnum/gsUnum.h
- src/CMakeLists.txt
- src/gsCore/gsConfig.h.in
- src/gsCore/gsMath.h
Apply accepted changes from stable to jit_fix
> Apply accepted changes from stable to jit_fix

- extensions/gsUnum/exprtk_unum_posit_adaptor.hpp
- extensions/gsUnum/exprtk_unum_posit_forward.hpp
Commit fixes problems with specialisation of exprtk for Unums.
> Fixed bugs in ExprTk adaptor for gsUnum extension

- src/gsSolver/gsIterativeSolver.h
Move assertion on preconditioner to constructor and clarify the meaning
of some of the others.
> Improve assertions in src/gsSolver/gsIterativeSolver.h:

- src/gsSolver/gsBlockOp.h
- src/gsSolver/gsBlockOp.hpp
* mark member variable appropriately
* getOperator shall not fail if the block is missing: It is supposed
to return a BasePtr which might be nullptr. The caller might use
this information to determine with blocks do exist.
> smaller improvements in gsBlockOp:

- src/gsCore/gsDofMapper.cpp
- src/gsCore/gsDofMapper.h
fixed two issues with tagged dofs. (missing swap and no sorting after marking)
> Fix tagged dof

- extensions/gsCoDiPack/exprtk_codi_rf_adaptor.hpp
- extensions/gsCoDiPack/exprtk_codi_rf_forward.hpp
- extensions/gsCoDiPack/exprtk_codi_rr_adaptor.hpp
- extensions/gsCoDiPack/exprtk_codi_rr_forward.hpp
> Fixed bug in CoDiPack extension

- src/gsUtils/gsCombinatorics.h
Adding a function to create the rotation matrices belonging to the permutation in cubeIsometry()
> cubeisometryMatrix

- external/rapidxml/rapidxml.hpp
- src/gsCore/gsBasis.hpp
- src/gsCore/gsFuncData.h
- src/gsIO/gsFileData.h
- src/gsIO/gsFileData.hpp
- src/gsIO/gsXml.h
- src/gsIO/gsXml.hpp
ps Plot precision will be added as well, on a next commit.
> Allow to change file-write precision

- src/gsIO/gsFileData.h
> Add more inforamtion to documentation

- cmake/gsJITConfigXml.cmake
Fixed: The build-type specific flags where not included correctly.
Added: Additional languages (CUDA, Fortran) can be activated by passing the optional arguments "CUDA" and or "Fortran"
> Updated script to generate JIT configuration file

- src/gsAssembler/gsAssembler.h
- src/gsAssembler/gsAssembler.hpp
- src/gsCore/gsFunction.h
- src/gsIO/gsFileData.hpp
fixed bug in gsFileData and gsAssembler, added output in gsFunction
> fixed smal issues n gsFileData, gsAssembler

- src/gsSolver/gsPatchPreconditionersCreator.hpp
This fixes a wrong index in line 543 (now 533) and improves the code quality
> Some improvements in gsSolver/gsPatchPreconditionersCreator.hpp

- src/gsAssembler/gsExpressions.h
IMPROVED: Doxygen Latex call of \nabla
> Doxygen-Latex nabla

- cmake/ctest_script.cmake
> fix continuous cdash script

- examples/multiGrid_example.cpp
- src/gsSolver/gsPatchPreconditionersCreator.hpp
- unittests/gsPreconditioner_test.cpp
This adds some more unittests (such that all gsPatchPreconditionerCreator functions are covered) and fixes some of those functions (concerning the ordering of the dimensions in the Kronecker products).
> Preconder updates

- src/gsCore/gsMultiPatch.h
@stefantakacs Now it's your turn - really..
> add empty line for cdash commit test

- filedata/domain2d/ldomain.xml
- filedata/volumes/fichera.xml
- filedata/volumes/twisted_fichera.xml
This allows computations on domains that are not completely trivial.
> Some more domains for filedata

- examples/adaptiveConvectionDiffusionReaction_example.cpp
- src/gsAssembler/gsCDRAssembler.h
- src/gsAssembler/gsVisitorCDR.h
fix for https://github.com/gismo/internal/issues/4
> fix for https://github.com/gismo/internal/issues/4

- CMakeLists.txt
I personally prefer not to be forced to build motor.
> Allow to build only one of the subprojects

- src/gsPde/gsBiharmonicPde.h
> Latex-correction

- cmake/ctest_script.cmake
> typo in example of ctest_script.cmake

- src/gsAssembler/gsAssembler.h
- src/gsAssembler/gsRemapInterface.h
- src/gsAssembler/gsRemapInterface.hpp
- src/gsCore/gsBoundary.h
- src/gsSolver/gsAdditiveOp.h
- src/gsTensor/gsTensorDomainBoundaryIterator.h
Some Doxygen comments
Make some internal things private
> Some fixes & improvements for gsRemapInterface; some doxygen stuff

- src/gsCore/gsTemplateTools.h
> hotfix replace int64_t with long long

- src/gsCore/gsAffineFunction.h
- src/gsCore/gsConstantFunction.h
- src/gsCore/gsFunctionExpr.h
to these polymorphic classes using handy make functions.
> Allow to make unique pointers

- src/gsIO/gsOptionList.cpp
- src/gsIO/gsOptionList.h
by forcing first column to be large enough in any case
> Improve printing of gsOptionList.cpp 

- examples/bSplineBasis_example.cpp
- examples/multiGrid_example.cpp
- examples/parametrization_example.cpp
use `--plot` as default command to plot for (almost) all examples.
> Unification of the "plot" command for command line

- src/gsCore/gsTemplateTools.h
this should fix https://cdash.ricam.oeaw.ac.at/viewBuildError.php?type=1&buildid=337199
> fix -Wsign-compare warning

- examples/adaptRefinementThb_example.cpp
- examples/adaptiveConvectionDiffusionReaction_example.cpp
- examples/assembly_example.cpp
- examples/bSplineBasis_example.cpp
- examples/bSplineCurve_example.cpp
- examples/bSplineSurface_example.cpp
- examples/basis_example.cpp
- examples/biharmonic_example.cpp
- examples/fitting_example.cpp
- examples/geometry_example.cpp
- examples/gsPatchFromBoundary.cpp
- examples/heatEquation_example.cpp
- examples/multiGrid_example.cpp
- examples/parametrization_example.cpp
- examples/poisson2_example.cpp
- examples/poissonTHB_example.cpp
- examples/thbRefinement_example.cpp
- examples/thbSplineBasis_example.cpp
- examples/triangulatedMeshToSolid_example.cpp
Give a unified hint on --plot .
> Some examples cleanup

- filedata/stl/patchLisa.stl
- filedata/stl/patchLisa_1.stl
set implicit normal vectors to correct direction
> fixed geometries for `parametrization_example`

- src/gsUtils/gsUtils.h
- unittests/gsAbs_Diff_test.cpp
- unittests/gsUtils_test.cpp
Unittests for gsUtils.h helper functions.
> add gsUtils.h Unittest

- src/gsCore/gsBasis.h
- src/gsNurbs/gsKnotVector.hpp
- src/gsTensor/gsTensorBasis.h
This pull request solves issues #322 (by improving the documentation of `active_into(...)`) and #324 (by fixing a bug in `gsKnotVector`).
> - [X] Have you added an explanation of what your changes do and why
Yes, this has been explained in issues #322 and #324.
> - [ ] Have you documented any new codes using Doxygen comments?
No, since it is a bugfix and an improvement of the documentation.
> - [ ] Have you written new tests or examples for your changes?
No, but I ran the unittests. Do you think I should write a new unittest for the change in `gsKnotVector`?
> Issues 322 and 324
