gismo/gismo

src/gsHSplines/gsHTensorBasis.h, src/gsHSplines/gsHTensorBasis.hpp
To support getting a connectivity mesh of the hierarchical tensor basis, I have re-arranged the existing code to provide this functionality. It does not impact the existing API.
=> Added per-level connectivity for hierarchical tensor basis

src/gsCore/gsDebug.h, src/gsCore/gsJITCompiler.h
* Unify the wording of GISMO_ASSERT and GISMO_ENSURE
* Write errors (also from GISMO_ASSERT) to gsWarn as they are real errors.
* Use "do {...} while(false)" everywhere to obtain a unified look-and-feel.
=> Some improvements for gsDebug.h:

src/gsCore/gsFunctionExpr.hpp
tested with GCC 6.4.0 Cxx 98 and 11
=> fix memory leak in gsFunctionExpr.hpp

src/gsCore/gsField.h, src/gsIO/gsWriteParaview.hpp, src/gsUtils/gsNorms.hpp
This provides also access to nPieces, if desired.
If the object is not based on gsMultiPatch, the number of patches is 1.
=> Fix gs field

src/gsAssembler/gsVisitorNitsche.h, src/gsAssembler/gsVisitorNitscheBiharmonic.h
In the 1D case with Nitsche's method for BC, we have element.getCellSize() = 0, leading to mu = Inf
Therefore, the following updates are proposed. 
-----
=> Penalty parameter updated for 1D case

src/gsCore/gsDofMapper.cpp, src/gsCore/gsDofMapper.h
This should allows for more flexibility, when using the dofmapper. The user can now permute the ordering of the dofs. The only restriction is, that the eliminated dofs have to be still ordered last (makes no sense otherwise).  Moreover, it is only allowed to perform a  permutation once (see also flag m_isPermuted). This could be implemented at some point, but I think is not required now. The permutation can be combined before.
It is then getting a bit more complex with the coupled dofs, since they may be mixed with the pure free dofs. In order to have a fast checking if a dofs is coupled (and which coupled idx it is), while having a small memory consumption, additional members are added to store precomputed information. Other functions are not affected.
=> Permutation of dofmapper indices

src/gsMultiGrid/gsMultiGrid.hpp
The solver on the coarsest grid level should - if possible - be built on sparse matrix technology. This is at least for multipatch domains of interest, because there the coarsest grid problem might still be large-scale and sparse.
The previous implementation might stay there as fallback, but with a warning if the size is too large.
=> gsMultiGridOp should take sparse matrices if available

src/gsCore/gsLinearAlgebra.h
Eigen's assertions call abort. This is not good if they happen within unittests. So, we might have thmen to throw exceptions, as GISMO_ASSERT does.
Defining such a macro is a customization point in Eigen:
http://eigen.tuxfamily.org/dox-3.2/TopicPreprocessorDirectives.html
=> Make Eigen exceptions to behave like G+Smo exceptions

src/gsSolver/gsGMRes.hpp
early exit in this function leads to a mismatch of matrix sizes later in gsGMRes<T>::finalizeIteration() with the effect that it crashes in line 49. 
Anyway I dont see a reason why this check is needed, the normal exit should be sufficient.
=> Bugfix in GMRES

src/gsMpi/gsMpiComm.h
function alltoall called the wrong MPI function
=> Bugfix in gsMpiComm.h

src/gsAssembler/gsAssemblerBase.h
use give for assignment of gsMultiPatch (rvalue instead of lvalue)
=> gsAssemblerBase: use give for gsMultiPatch (rvalue instead of lvalue)

src/gsCore/gsMemory.h
removed gsMemory::safe(T *x), also done in devel
typo in doc
=> remove gsMemory::safe(T *x)

src/gsCore/gsBoundary.cpp, src/gsCore/gsBoundary.h
We can ask a patchCorner for the coressponding patchSides, but we cannot ask a patchSide for the corresponding patchCorners.
This commit fixes that.
=> add patchSide::getContainedCorners (int dim, std::vector<patchCorner> &corners)

cmake/gsConfig.cmake
Updated documentation about `index_t` to include `int32_t` and `int64_t` in the CMake documentation.
=> Updated documentation

src/gsCore/gsBasis.hpp
clang claims:
src/gsCore/gsBasis.hpp:438:1: warning: all paths through this function will call itself [-Winfinite-recursion]
and I concur.
I do not know if this is the best possible fix.
=> fix error in gsBasis

src/gsModeling/gsPlanarDomain.h, src/gsModeling/gsPlanarDomain.hpp, src/gsModeling/gsTrimSurface.h, src/gsModeling/gsTrimSurface.hpp, src/gsSolver/gsMatrixOp.h, src/gsSolver/gsSimplePreconditioners.h
Comes from old code, where smart ptrs where defined differently.
=> remove some uneeded typename

cmake/gismoUse.cmake
Extensions in the development branch were never treated correctly because `gismo_dev_EXTENSIONS` was never included in the final linking step. This commit fixes this problem.
=> Enable detection of gismo_dev_EXTENSIONS

src/gsAssembler/gsAssembler.h
dimensions were not agreeing when calling md.jacobians().block(..). Led to a crash in gsShellMixed_test (devel).
=> fixed a bug in normal()

src/gsCore/gsMath.h
Added `std::real`, `std::imag`, and `std::conj` to `gsMath` to make it available within the G+Smo namespace.
Also added dummy implementations of the functions `frexp` and `ldexp` for UNUM types.
=> Added std::real, std::imag, and std::conj to gsMath to make it

src/gsCore/gsPiecewiseFunction.h
Added a function to clear the container with gsFunction * pointers.
Functionality similar to gsMultiPatch::clear().
Necessary to for multipatch stress functions in gsElasticity/gsElasticityAssembler.hpp at line 114  - in gsElasticityAssembler::constructCauchyStresses
=> gsPiecewiseFunction - add clear()

extensions/gsParasolid/gsWriteParasolid.hpp
The function `createPK_BSURF` from extensions/gsParasolid/gsWriteParasolid swaps _u_- and _v_- directions (the 0-th parametric dimension of Gismo becomes _v_ and the 1-st becomes _u_ in Parasolid). This is caused by Parasolid and Gismo storing the control points in different order (row-wise vs. col-wise).
While the geometry remains unchanged, it is still a bug, as we have to transpose after each export. I have committed a simple solution: we create a `PK_BSURF` with the directions swapped and then transpose the geometry with `PK_BSURF_reparameterise`.
We are the sole users of the Parasolid interface, so I did not add any further tests to Gismo.
=> Transposing PK_BSURF in gsWriteParasolid.

src/gsAssembler/gsAssembler.h, src/gsAssembler/gsAssembler.hpp
Why copying the visitor? This may require a copy constructor
=> gsAssembler::updateSolution works for vector valued functions

CMakeLists.txt
This fixes the linker error #292 where gsElasticity examples can't be compiled. I don't know why, but apparently https://github.com/gismo/gismo/blob/8f2e332e33249cf6275327f0bb97b64daffceff4/CMakeLists.txt#L393
has to come before https://github.com/gismo/gismo/blob/8f2e332e33249cf6275327f0bb97b64daffceff4/CMakeLists.txt#L313
as it used to be before the 8a6c6d0fbc02d733165e20a8bc0291f6f7da37b6. It probably has to be the same for the rest of the submodules, but I didn't touch it
=> Fix gsElastity linker error

src/gsCore/gsMath.h, src/gsCore/gsTemplateTools.h, unittests/gsMakeUnsigned.cpp
On some code (unsupported, like [gsIETIdG_experimental.cpp#L145](https://github.com/gismo/unsupported/blob/b36880528353bac9826de7892fe4338679e2032e/examples/gsIETIdG_experimental.cpp#L145)) there is abs(a - b) used to find out the distance of 2 indexes.
Since this will not work with size_t, and is buggy in special cases, it would make sense to add an error free implementation that works well with all integer types.
=> add unsigned T abs_diff(T a, T b)

src/gsUtils/gsCombinatorics.h
precomputed array has 13 elements, 0 .. 12
=> fix overflow in gsCombinatorics.h

cmake/gsConfig.cmake
We cannot allow index_t to be a unsigned type (including size_t) because this breaks much of our programming logic.
(This is taken out from pr #306 by @codewerfer)
=> change possibilities for index_t

src/gsSolver/gsAdditiveOp.h, src/gsSolver/gsPatchPreconditionersCreator.hpp, src/gsSolver/gsPreconditioner.h
We can directly use the virtual function gsBasis<T>::component() instead of casting to gsTensorBSplineBasis first. Only one function really relies on B-Splines.
=> simplify gsPatchPreconditionersCreator

.gitignore, external/Eigen/src/Core/util/Macros.h, src/gsAssembler/gsExprAssembler.h, src/gsAssembler/gsExpressions.h, src/gsCore/gsBoxTopology.cpp, src/gsCore/gsDebug.h, src/gsCore/gsExport.h.in, src/gsCore/gsJITCompiler.h, src/gsCore/gsMemory.h, src/gsCore/gsTemplateTools.h, src/gsIO/gsCmdLine.cpp, src/gsIO/gsFileManager.cpp, src/gsModeling/gsParametrization.hpp, src/gsUtils/gsStopwatch.h, src/gsUtils/gsUtils.h, unittests/gsMoveSemantics_test.cpp, unittests/gsUtils_test.cpp
see https://github.com/gismo/internal/issues/10
fixes for:
=> use _MSVC_LANG, as MSVC doesn't set _cplusplus to correct value

extensions/gsParasolid/gsWriteParasolid.cpp, extensions/gsParasolid/gsWriteParasolid.h, extensions/gsParasolid/gsWriteParasolid.hpp
This is the branch corresponding to issue #337 (sorry for the wrong number).
New functionality for gsParasolid: convert a gsTensorBSpline<2> into a PK_SHEET and export it.
Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.
Code submitted to the stable branch should be clean, well-documented
and free of bugs.
request:
-----
=> Issue #337: exporting a PK_SHEET from extensions/gsParasolid

src/gsAssembler/gsExprAssembler.h, src/gsCore/gsDofMapper.cpp, src/gsCore/gsDofMapper.h, src/gsCore/gsDofMapper.hpp, src/gsCore/gsDofMapper_.cpp
The interface is extended by an arguement for the component, eg.
gsDofMapper::index(local-dof, patch, component)
There is no change in the behaviour when 1 component is used.
Restrictions:
1. The basis must be of equal size for all components.
2. DoFs on different components cannot be merged.
=> Dof mapper handles vector variables

extensions/gsParasolid/gsWriteParasolid.hpp
When I was fixing the swapped _u_- and _v_-directions in Parasolid export (issue #290), I missed one of them. The current PR fixes the problem.
Parasolid and Gismo store coefficients in a different order. In the past, this meant that the Parasolid export was returning a geometrically correct surface but with _u_ and _v_ swapped. In issue #290, I fixed this for all our calls of the functions in `gsWriteParasolid.hpp`. However, I did not realize that there are functions in the file that call other functions from the _same_ file and did not fix the transposition for those. The current PR fixes this omission.
Pull requests can only be merged after at least one review (and
approval) from @gismo/admins.
Code submitted to the stable branch should be clean, well-documented
and free of bugs. …
=> Bugfix: a forgotten swap of parameters from issue #290

examples/constrained_fitting.cpp, src/gsHSplines/gsHFitting.h, src/gsModeling/gsFitting.h, src/gsModeling/gsFitting.hpp
I have extended the least squares fitting algorithm to allow enforcing linear constraints on the coefficients.
It is described in Prautzsch, Boehm, Paluszny: Bezier and B-spline techniques, Section 4.7.
Instead of minimizing the L^2 error among all surfaces, it now minimizes the L^2 error among all surfaces satisfying the constraints. If no constraints are given, `gsFitting` works as before.
For instance, in `gsHFitting` it is now possible to prescribe the values along some of the boundary sides. The new example `constrained_fitting` tries to show, how it can be used.
It is useful in practice if you want to fit a patch of data but the result has to be sewn to some prescribed form.
The functionality in `gsFitting` is rather general and can be used later on. The parts involving patch sides …
=> Least squares fitting with linear constraints.

src/gsCore/gsGeometry.hpp, src/gsIO/gsWriteParaview.hpp, src/gsUtils/gsMesh/gsMesh.h, src/gsUtils/gsMesh/gsMesh.hpp
This pull request does three things:
1. It implements the enhancement discussed in issue #347 (commit 3b13568d17dec7800b61d7dd1314f8fe73ba9ba8).
2. It contains a bugfix to issue #348 (commit 7f4d38546d3878bbb45ba42a73caa5ee12fbfcb4).
3. Documentation of several functions in `gsMesh`, which were used for the first two points, has been made and updated (commit acaaf6fb7ffb8da8fc1738b92437de0ad81e8762).
**Yes**, in the form of issues #347 and #348 .
There is not much new code but existing Doxygen has been improved.
**No**. Both of the issues improve the visualisation with Paraview, which would be difficult to capture in an automated test.
-----
=> Paraview mesh bug
